[2024-11-28 17:13:25,829] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sw/arch/RHEL8/EB_production/2023/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 48, in <module>
    from .loss.loss_utils import LOSS_MAPPING
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/loss/loss_utils.py", line 19, in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/loss/loss_deformable_detr.py", line 4, in <module>
    from ..image_transforms import center_to_corners_format
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/home/scur2847/.local/lib/python3.11/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scur2847/.local/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scur2847/.local/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/gpfs/home1/scur2847/ir2-less-data/evaluation/eval/mmlu/run_eval.py", line 12, in <module>
    from eval.utils import (dynamic_import_function, get_next_word_predictions,
  File "/gpfs/home1/scur2847/ir2-less-data/evaluation/eval/utils.py", line 10, in <module>
    from open_instruct.finetune import encode_with_prompt_completion_format
  File "/gpfs/home1/scur2847/open-instruct/open_instruct/finetune.py", line 38, in <module>
    from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
  File "/home/scur2847/.local/lib/python3.11/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/scur2847/.local/lib/python3.11/site-packages/peft/auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/scur2847/.local/lib/python3.11/site-packages/peft/mapping.py", line 23, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/scur2847/.local/lib/python3.11/site-packages/peft/mixed_model.py", line 30, in <module>
    from .peft_model import PeftModel
  File "/home/scur2847/.local/lib/python3.11/site-packages/peft/peft_model.py", line 35, in <module>
    from transformers import PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scur2847/.local/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
MMLU Evaluation Result: 50.1566728386269800%

JOB STATISTICS
==============
Job ID: 8806574
Cluster: snellius
User/Group: scur2847/scur2847
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:06
CPU Efficiency: 1.97% of 00:05:04 core-walltime
Job Wall-clock time: 00:00:19
Memory Utilized: 2.40 MB
Memory Efficiency: 0.00% of 180.00 GB
